Add files via upload
UBIKhr/web pull request #45
Opened 2021-01-13 18:30 UTC by lukaskywalk

Članak o NFT-evima

2021-01-13 22:07 UTC, morrigan commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +title: "UBIK NFT kolekcija 2021 -"
```suggestion
title: "UBIK-ova prva NFT kolekcija"
```

2021-01-13 22:07 UTC, morrigan commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +tags: ["NFT", "UO"]
```suggestion
tags: ["NFT", "članovi"]
```

2021-01-13 22:10 UTC, morrigan submitted a review, later dismissed

2021-01-14 09:05 UTC, Swader requested changes

2021-01-14 09:05 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +Počela je nova 2021 godina i u najboljoj maniri “New Year New Me” krilatice i mi smo odlučili okrenuti novi list, nadam se da ste primjetili. Izabrali smo novi upravni odbor, predstavili plan razvoja
```suggestion
Počela je nova 2021 godina i u najboljoj maniri “New Year New Me” krilatice i mi smo odlučili okrenuti novi list, nadam se da ste primjetili. Izabrali smo novi upravni odbor, predstavili plan razvoja za 2021., osnovali savjetodavni odbor i reorganizirali sustav članstva te pripremamo godinu bogatu aktivnostima. Više o tome malo kasnije. Sada bismo se htjeli osvrnuti na osobni doprinos nekih pojedinaca koji su uskočili u vatru u trenutcima kada je bilo najkompliciranije i podsjetiti da te zasluge nikada neće biti zaboravljene. 
```

2021-01-14 09:05 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +Ovo definitivno nije patetična izjava koja se šalje “prvoborcima” nego isticanje činjenica. Da se osiguramo da se zaista ne zaboravi, odlučili smo kao udruga izdati posebnu seriju NFT-a. Oni će biti
```suggestion
Ovo definitivno nije patetična izjava koja se šalje “prvoborcima” nego isticanje činjenica. Da se osiguramo da se zaista ne zaboravi, odlučili smo kao udruga izdati posebnu seriju [NFT](https://bitfalls.com/hr/2018/10/15/the-last-nft-non-fungible-token-explanation-post-youll-ever-need/)-eva. Oni će biti izdavani svim prethodnim članovima upravnog odbora udruge koji su zadužili ne samo udrugu neko i kripto zajednicu u Hrvatskoj općenito. NFT-eve možte vidjeti na linkovima niže : 
```

2021-01-14 09:05 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +
Ovi prazni redovi nisu potrebni - markdown miče empty lines i kondenzira ih u jedan. Za separaciju sekcija koristiš section headings (`##` iliti H2 itd), ili horizontalne crte za odvajanje sadržaja (`---`).

2021-01-14 09:05 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +Upravni Odbor UBIK-a i cijelokupno članstvo se želi zahvaliti : Luki Klanciru, Ivanu Vorasu, Nikoli Jokiću i Vedranu Kajiću. Hvala svima od srca na svemu do sada i vidimo se uskoro na prvom UBIK even
```suggestion
Upravni Odbor UBIK-a i cijelokupno članstvo se želi zahvaliti: Luki Klanciru, Ivanu Vorasu, Nikoli Jokiću i Vedranu Kajiću. Hvala svima od srca na svemu do sada i vidimo se uskoro na prvom UBIK eventu 2021 (stay tuned).
```

2021-01-14 15:21 UTC, Swader requested changes

2021-01-14 15:21 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +Počela je nova 2021 godina i u najboljoj maniri “New Year New Me” krilatice i mi smo odlučili okrenuti novi list, nadam se da ste primjetili. Izabrali smo novi upravni odbor, predstavili plan razvoja
```suggestion
Počela je nova 2021 godina i u najboljoj maniri “New Year New Me” krilatice i mi smo odlučili okrenuti novi list, nadam se da ste primjetili. Izabrali smo novi upravni odbor, predstavili plan razvoja za 2021., osnovali savjetodavni odbor i reorganizirali sustav članstva te pripremamo godinu bogatu aktivnostima. Više o tome malo kasnije. Sada bismo se htjeli osvrnuti na osobni doprinos nekih pojedinaca koji su uskočili u vatru u trenutcima kada je bilo najkompliciranije i podsjetiti da te zasluge nikada neće biti zaboravljene. Ovo definitivno nije patetična izjava koja se šalje “prvoborcima” nego isticanje činjenica. 

Da se osiguramo da se zaista ne zaboravi, odlučili smo kao udruga izdati posebnu seriju [NFT](https://bitfalls.com/hr/2018/10/15/the-last-nft-non-fungible-token-explanation-post-youll-ever-need/)-eva. Oni će biti izdavani svim prethodnim članovima upravnog odbora udruge koji su zadužili ne samo udrugu neko i kripto zajednicu u Hrvatskoj općenito. NFT-eve možete vidjeti na linkovima niže : 
```

2021-01-14 15:21 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +[![](images/blog/ubik_NFT.png)](https://app.rarible.com/user/0x16f0210fbc468da71d47f04e95e4804f46bc2a59/collectibles)
```suggestion
[![](images/blog/ubik_NFT.png)](https://app.rarible.com/user/0x16f0210fbc468da71d47f04e95e4804f46bc2a59/collectibles)

```

2021-01-15 10:59 UTC, Swader requested changes

2021-01-15 10:59 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +Počela je nova 2021 godina i u najboljoj maniri “New Year New Me” krilatice i mi smo odlučili okrenuti novi list, nadam se da ste primjetili. Izabrali smo novi upravni odbor, predstavili plan razvoja
```suggestion
Počela je nova 2021. godina i u najboljoj maniri “New Year New Me” krilatice i mi smo odlučili okrenuti novi list, nadam se da ste primjetili. Izabrali smo novi upravni odbor, predstavili plan razvoja za 2021., osnovali savjetodavni odbor i reorganizirali sustav članstva te pripremamo godinu bogatu aktivnostima. Više o tome malo kasnije. Sada bismo se htjeli osvrnuti na osobni doprinos nekih pojedinaca koji su uskočili u vatru u trenutcima kada je bilo najkompliciranije i podsjetiti da te zasluge nikada neće biti zaboravljene. Ovo definitivno nije patetična izjava koja se šalje “prvoborcima” nego isticanje činjenica. 
```

2021-01-15 10:59 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +Da se osiguramo da se zaista ne zaboravi, odlučili smo kao udruga izdati posebnu seriju [NFT](https://bitfalls.com/hr/2018/10/15/the-last-nft-non-fungible-token-explanation-post-youll-ever-need/)-eva
```suggestion
Da se osiguramo da se zaista ne zaboravi, odlučili smo kao udruga izdati posebnu seriju [NFT](https://bitfalls.com/hr/2018/10/15/the-last-nft-non-fungible-token-explanation-post-youll-ever-need/)-eva. Oni će biti izdavani svim prethodnim članovima upravnog odbora udruge koji su zadužili ne samo udrugu neko i kripto zajednicu u Hrvatskoj općenito. NFT-eve možete vidjeti na linkovima niže: 
```

2021-01-18 08:58 UTC, Swader requested changes

2021-01-18 08:58 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +
Di su `---`? Frontmatter treba biti okružen `---` s obje strane!

2021-01-18 09:01 UTC, lukaskywalk commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +
evo poslao ispravak

2021-01-18 09:04 UTC, Swader commented on site/content/english/blog/UBIK NFT kolekcija 2021 -.md
> +---
Fali new line

2021-01-18 09:07 UTC, Swader approved these changes

2021-01-18 09:07 UTC, merged